### ISSUE TITLE
Add Python3.7 support

### ISSUE THREAD

**Issue by larsbutler** [geomet/geomet#41]
`geomet` already supports Python3.6 so it shouldn't be a stretch to support 3.7 as well. However, it would need to be explicitly added and tested.

**Comment by applecool** [comment]
This is a freaking sweet library. Thanks for building it :) 👍

**Comment by larsbutler** [comment]
Hey, thanks @applecool !

**Comment by pbryan** [comment]
On Python 3.7.4, all tests pass when running:
$ python3 ./setup.py test

**Comment by larsbutler** [comment]
@pbryan Hey, thanks for testing that. I'll see if I can fix that and button up 3.7 support.

**Comment by larsbutler** [comment]
Solved by #45 and released with version [0.2.1](https://github.com/geomet/geomet/releases/tag/0.2.1) to [PyPI](https://pypi.org/project/geomet/0.2.1/).

**Comment by pbryan** [comment]
I see the Python dependency is < 3.8. You seem to be importing collections.abc based on Python version, which should be forward-compatible. Any other reason you may be limiting future 3.x version of Python?

**Comment by larsbutler** [comment]
Mainly just lack of testing with 3.8 is the reason, that’s all. I was mostly focused on getting the 3.7 support released.

**Comment by pbryan** [comment]
OK, cool. Would you be willing to drop the < 3.8 restriction? It's requiring dependents to also restrict future versions of Python.

**Comment by QuLogic** [comment]
There does not appear to be [any issue](https://koji.fedoraproject.org/koji/buildinfo?buildID=1363770) building against Python 3.8.

**Comment by pbryan** [comment]
A build tool like Poetry traverses the entire graph to determine the correct versions of packages to pull-in. When a package that has a dependency on Python"^3.6" (equivalent: >= 3.6, <4), and also depends on GeoMet, it can't resolve the dependency because GeoMet is guarding against future 3.x versions of Python (<3.8).
