### ISSUE TITLE
conda-forge submission

### ISSUE THREAD

**Issue by Thingus** [geomet/geomet#43]
Hi maintainers
I'm putting a library up on Conda-Forge, and it contains this library as a dependency. Are you alright with my using conda skeleton to submit this repository to conda-forge? I'm happy to list myself as the maintainer, and it includes all references back to this repository.
The library in question:
https://github.com/clcr/pyeo
The conda forge pull request:
conda-forge/staged-recipes#8972

**Comment by larsbutler** [comment]
Hi @Thingus,

Thanks for checking in on this! As long as the Apache license is satisfied, feel free. (See section 4 in particular for conditions of redistribution: https://github.com/geomet/geomet/blob/master/LICENSE. It’s pretty much what you’d expect: basically as long as the license and copyright notice are retained in distributed copies, you’re good.)

I’m glad you’re finding the library useful. Any other questions or concerns, let me know!

Thanks!
-Lars

**Comment by Thingus** [comment]
The license is included in the tarball, so no problems there.
Much obliged!

**Comment by Thingus** [comment]
Actually, my mistake; the license was not included in the tarball, but is on the github page. I think it might be out of step with the PyPI release.

**Comment by larsbutler** [comment]
@Thingus 

> Actually, my mistake; the license was not included in the tarball, but is on the github page. I think it might be out of step with the PyPI release.

Thanks for pointing that out. I'll double check to make sure the package release is correct. There _should_ be a license included in the source package.

**Comment by larsbutler** [comment]
@Thingus Apologies for taking so long to loop back on this. The latest release of `geomet` should have the license file in the source package and fixes some silliness with the placement of install artifacts.
