### ISSUE TITLE
Update documentation and project metadata to include support for GeoPackage

### ISSUE THREAD

**Issue by larsbutler** [geomet/geomet#59]
With the addition of #56, WKT, WKB, and GeoJSON aren't the only supported formats anymore.

Prerequisites:
- [x] Merge of #56 
- [x] Resolution of #42 
- [x] New minor version (0.3.0) release to PyPI

Once these prereqs are done, update:
- [x] The GitHub repo title
- [x] Update GitHub repo "topics" to include `geopackage`
- [ ] Update any docs which are similar to "GeoMet - Convert GeoJSON to WKT/WKB, and vice versa" <-- include GeoPackage in the list of supported formats.

**Comment by tomplex** [comment]
Hey @larsbutler, when do you think we could get a new release out? I want to use the geopackage serializer at work and I don't want to have to re-write it. =)

**Comment by larsbutler** [comment]
@tomplex Sure, I'll get on that. I'll put up a few PRs; it would be great to get your review on them.

**Comment by tomplex** [comment]
Absolutely! Will do.

**Comment by larsbutler** [comment]
Cool. First one is easy: https://github.com/geomet/geomet/pull/67. :)
