### ISSUE TITLE
Release version 1.0.0

### ISSUE THREAD

**Issue by larsbutler** [geomet/geomet#85]
Several significant changes have happened since the last [0.3.0 release](https://github.com/geomet/geomet/pull/69). For instance:
- #73
- #77 
- #79 
- #82 
- #84 

A few things are needed before this release is done:
- [x] Update documentation on release procedures, and clearly define the process. With the addition of branch protection and a new automation workflow in CircleCI, there needs to be a clearly defined process to streamline future release.
- [x] Update repository, GitHub org, and README to reflect the addition of support for new geospatial formats (related: https://github.com/geomet/geomet/issues/59). For instance, instead of saying we just convert between GeoJSON/WKT/WKB, I think we should say something more general like "Conversion library for common geospatial data formats".
- [x] Update repository tags to include new supported formats (esri json, geopackage, etc.) to make the library easier to find.
- [x] Release 1.0.0 package to PyPI.
- [x] Create and push a 1.0.0 tag to GitHub.
- [x] Compile release notes and create a release for 1.0.0 on GitHub.

**Comment by larsbutler** [comment]
PyPI release solved by #87.

**Comment by QuLogic** [comment]
The 1.0.0 tag appears to be missing here on GitHub.

**Comment by larsbutler** [comment]
> The 1.0.0 tag appears to be missing here on GitHub.

Fixed. :)
