### ISSUE TITLE
six is not required

### ISSUE THREAD

**Issue by pgajdos** [geomet/geomet#90]
I think six is not required anymore since drop support of python 2.

**Comment by achapkowski** [comment]
You would have to change https://github.com/geomet/geomet/blob/8d2b8f281ef7a919fa0cc9dd5230304d9ff71bd2/geomet/wkt.py#L137 to use `next`
and change https://github.com/geomet/geomet/blob/8d2b8f281ef7a919fa0cc9dd5230304d9ff71bd2/geomet/util.py#L118 to be just str instead of six.string_types.
